version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.5.0
    steps:
      - checkout
      - run:
          command: |
            npm install
            npx playwright install chrome

      - run:
          name: Running tests
          no_output_timeout: 180m
          command: |
            npx playwright test --project="Google Chrome"

      - run:
          name: generate allure report
          command: |
              allure generate --clean
          when: always

      - store_artifacts:
            path: /home/circleci/project/allure-report

          