version: 2.1
jobs:
  build:
    docker:
       # Use the official CircleCI Node.js image
      - image: circleci/node:latest-browsers

    steps:
      - checkout

      - run:
          name: Install OpenJDK 11
          command: |
            sudo apt-get update && sudo apt-get install openjdk-11-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
            java -version

      - run:
          name: Install dependencies
          command: |
            npm install
            npx playwright install chrome
            sudo npm install -g allure-commandline

      - run:
          name: Running tests
          no_output_timeout: 180m
          command: |
            npx playwright test --project="Google Chrome"

      - run:
          name: generate allure report
          command: |
              allure generate --clean
          when: always

      - store_artifacts:
            path: /home/circleci/project/allure-report

    environment:
      # Use the environment variables for Docker Hub credentials
        DOCKER_LOGIN: ${DOCKER_USERNAME}
        DOCKER_PASSWORD: ${DOCKER_PASSWORD}

          