version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get install -y nodejs
            sudo apt-get install -y build-essential
            sudo apt install npm
            npm install
            npx playwright install chrome
            sudo npm install -g allure-commandline

      - run:
          name: Running tests
          no_output_timeout: 180m
          command: |
            npx playwright test --project="Google Chrome"

      - run:
          name: generate allure report
          command: |
              allure generate --clean
          when: always

      - store_artifacts:
            path: /home/circleci/project/allure-report

          