version: 2.1
jobs:
  build:
    docker:
       # Use the official CircleCI Node.js image
      - image: circleci/node:latest-browsers
      # Add another image for Allure
      - image: allureframework/allure2:latest
    steps:
      - checkout

      - run:
          command: |
            npm install
            npx playwright install chrome
            sudo npm install -g allure-commandline

      - run:
          name: Running tests
          no_output_timeout: 180m
          command: |
            npx playwright test --project="Google Chrome"

      - run:
          name: generate allure report
          command: |
              allure generate --clean
          when: always

      - store_artifacts:
            path: /home/circleci/project/allure-report

    environment:
      # Use the environment variables for Docker Hub credentials
        DOCKER_LOGIN: ${DOCKER_USERNAME}
        DOCKER_PASSWORD: ${DOCKER_PASSWORD}

          